FROM ubuntu:22.04

# see https://github.com/moby/moby/issues/4032#issuecomment-192327844
ARG DEBIAN_FRONTEND=noninteractive

# ARG for quick switch to a given ubuntu mirror
ARG apt_archive="http://archive.ubuntu.com"

# user/group precreated explicitly with fixed uid/gid on purpose.
RUN sed -i "s|http://archive.ubuntu.com|${apt_archive}|g" /etc/apt/sources.list \
    && groupadd -r clickhouse --gid=101 \
    && useradd -r -g clickhouse --uid=101 --home-dir=/var/lib/clickhouse --shell=/bin/bash clickhouse \
    && apt-get update \
    && apt-get install --yes --no-install-recommends \
        busybox \
        ca-certificates \
        locales \
        tzdata \
    && busybox --install -s \
    && rm -rf /var/lib/apt/lists/* /var/cache/debconf /tmp/*

# Copy the locally built binary
COPY build/programs/clickhouse /tmp/clickhouse

# Install using clickhouse's built-in install command
RUN chmod +x /tmp/clickhouse \
    && /tmp/clickhouse install --user "clickhouse" --group "clickhouse" \
    && rm -rf /tmp/*

# post install
RUN clickhouse-local -q 'SELECT * FROM system.build_options' \
    && mkdir -p /var/lib/clickhouse /var/log/clickhouse-server /etc/clickhouse-server /etc/clickhouse-client \
    && chmod ugo+Xrw -R /var/lib/clickhouse /var/log/clickhouse-server /etc/clickhouse-server /etc/clickhouse-client

RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV TZ=UTC

RUN mkdir -p /docker-entrypoint-initdb.d

COPY docker/server/docker_related_config.xml /etc/clickhouse-server/config.d/
COPY docker/server/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 9000 8123 9009
VOLUME /var/lib/clickhouse

ENV CLICKHOUSE_CONFIG=/etc/clickhouse-server/config.xml

ENTRYPOINT ["/entrypoint.sh"]
